version: "3.9"

name: survivor-seminar

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: jeb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d jeb"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks: [app-net]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      # Database connection
      DATABASE_URL: postgres://postgres:postgres@db:5432/jeb?sslmode=disable

      # JWT & auth
      JWT_SECRET: <secret>

      # Optional integrations
      JEB_GROUP_TOKEN: ""
      EMAIL_FROM: noreply@example.com
      SMTP_URL: ""

      # S3
      PUBLIC_BASE_URL: ""
      S3_BUCKET: ""
      S3_REGION: ""
      S3_ENDPOINT: ""
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "1111:1111"
    networks: [app-net]

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: /api/v1
      BACKEND_ORIGIN: http://backend:1111
      SKIP_ENV_VALIDATION: "1"
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks: [app-net]

networks:
  app-net:
    driver: bridge

volumes:
  db-data:
    driver: local

