#!/bin/sh

printf "starting web pre-commit checks..."

cd web || exit
npx lint-staged

printf "web pre-commit checks done!"

cd .. || exit

printf "starting server pre-commit checks..."

cd backend || exit

go fmt ./...
go build ./... || exit 1
go test ./... || exit 1

printf "server pre-commit checks done!"