name: mirror

on: push

env:
  MIRROR_URL: 'git@github.com:EpitechPGE3-2025/G-SVR-500-PAR-5-1-survivor-10.git'

jobs:
  push_to_mirror:
    name: Push to mirror
    runs-on: ubuntu-latest

    if: github.repository != 'EpitechPGE3-2025/G-SVR-500-PAR-5-1-survivor-10' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirroring to the repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          target_repo_url: ${{ env.MIRROR_URL }}
